### ISSUE TITLE
[2.3.4] Project Plan Updates

### ISSUE THREAD

**Issue by mvchello** [lowyisan/INF2001_P6-6#115]
**What is the task about?** The task involves documenting the updates of the project and how it will progress further.

**What are the goals of the task?** Provide documentation through the form of a Gantt Chart that focuses on the future project plan.

**Success or Completion Criteria:** Provide a well-documented and up-to-date Gantt Chart the reflects the project plan for M1, M2, and M3.

**Allocated time:** 4 days

**Start date and end date:** [Start Date: 25/10/23], [End Date: 28/10/23]

**Owner:** Michelle & Yi San

**Status of the task:** To-Do

**Priority:** Medium

**Comment by mvchello** [comment]
**Describe the work done in detail.**
Changes were made and reflected in the Gantt Chart with respect to the M1 feedback accordingly. Modifications to the team's project plan moving forward were also made.

**Has this work been committed to the repository?**
No work is needed to commit to the repository.

**How does the work affect success or completion criteria?**
It is important to know to make changes according to the M1 feedback as it corrects the team's direction as the project progresses.

**Start date and end date:**
[Start Date: 25/10/23]
[End Date: 28/10/23]

**Comment by lowyisan** [comment]
**Describe the work done in detail.**
For this task, I was responsible in assisting in the updating and modifying of the Gantt Chart to reflect the project plan for M1, M2, and M3. Adjustments to the timeline and task dependencies were made to ensure the project plan is aligned with our project goals and objectives.

**Has this work been committed to the repository?**
No work is needed to commit to the repository.

**How does the work affect success or completion criteria?**
This work directly contributes to the success and completion criteria of the task as it ensures that the project plan is accurate, up-to-date, and responsive to the feedback received.

**Start date and end date:**
[Start Date: 25/10/23]
[End Date: 27/10/23]
