### ISSUE TITLE
[2.4] M2 Presentation

### ISSUE THREAD

**Issue by KeeHanXiang** [lowyisan/INF2001_P6-6#119]
**What is the task about?** The task involves presenting the changes made from M1, as well as the Software Design that the team has come up with.

**What are the goals of the task?** Reflect the needed changes from M1 to M2. Create the various Software Designs in terms of diagrams (class diagram, component diagram, and sequence diagram) for M2.

**Success or Completion Criteria:** Present well-documented and up-to-date information regarding the project.

**Allocated time:** 1 day

**Start date and end date:** [Start Date: 02/11/23], [End Date: 02/11/23]

**Owner:** Han Xiang & Jin Hao

**Status of the task:** To-Do

**Priority**: Medium

**Comment by KeeHanXiang** [comment]
**Describe the work done in detail.**
Presented sections on sequence diagram and component diagram.

**Has this work been committed to the repository?**
No work is needed to commit to the repository.

**How does the work affect success or completion criteria?**
This task involves explaining how the diagrams were crafted and presenting the work done by the team.

Start date and end date:
[Start Date: 02/11/23]
[End Date: 02/11/23]

**Comment by ThJin** [comment]
**Describe the work done in detail.**
The work involved presenting the changes made from Milestone 1 to Milestone 2 and the software design that the team developed.

**Has this work been committed to the repository?**
The work does not involve any code. Therefore, no repository commits is needed.

**How does the work affect success or completion criteria?**
The work ensures that all stakeholders have a comprehensive understanding of the project's progress and design decisions.

Start date and end date:
[Start Date: 02/11/23]
[End Date: 02/11/23]
