### ISSUE TITLE
[2.3.1] Introduction

### ISSUE THREAD

**Issue by mvchello** [lowyisan/INF2001_P6-6#120]
What is the task about? This task involves updating readers on the product scope, references, and acknowledgements that were added in lieu of the feedback from M1.

What are the goals of the task? The goal is to ensure that the documentation is updated.

Success or Completion Criteria: All necessary changed and acknowledgements were made.

Allocated time: 1 day

Start date and end date: [Start Date: 16/10/23], [End Date: 16/10/23]

Owner: All

Status of the task: To-Do

Priority: Medium

**Comment by lowyisan** [comment]
**Describe the work done in detail:**
Acknowledgments have been added as per the feedback from Milestone 1. The acknowledgments section now includes recognition of contributors, mentors, and sources of inspiration. There are no references added as the document does not refer to any external sources.

**Has this work been committed to the repository?**
No, this task do not involve code changes. Therefore, no commits were made to the repository for this task.

**How does the work affect success or completion criteria?**
This work contributes to a more comprehensive and well-documented report, acknowledging those who have influenced and contributed to the project. It ensures that the project documentation is complete and in compliance with standard documentation practices.

**Start date and end date:**
Start Date: 16/10/23
End Date: 16/10/23

**Comment by mvchello** [comment]
**Describe the work done in detail.**
Documentation of the product scope changes has been written. As there were no problems with the product scope that was written in M1, no changes were made.

**Has this work been committed to the repository?**
No work is needed to commit to the repository.

**How does the work affect success or completion criteria?**
It is important to updates such information in the documentation as it alerts whoever it may concern the state of the project and what the team is working towards.

**Start date and end date:**
[Start Date: 16/10/23]
[End Date: 16/10/23]
