### ISSUE TITLE
[2.3.3.1] Class Diagram

### ISSUE THREAD

**Issue by lowyisan** [lowyisan/INF2001_P6-6#125]
What is the task about? This task involves thoroughly documenting the class diagram that represents the software system.

What are the goals of the task? The primary goal is to provide a comprehensive and detailed description of the class diagram. This includes specifying classes, their attributes, methods, and relationships in a clear and organised manner.

Success or Completion Criteria: The task will be considered successful when a well-documented class diagram is available, accurately depicting the structure of the software system. The diagram should provide a clear representation of classes, their attributes, methods, and relationships. It should also include a clear description of the various parts of the class diagram.

Owner: Yi San and Jin Hao

Allocated time: 5 days

Start Date: 24/10/23

End Date: 28/10/23

Status of the task: To-Do

Priority: Medium

**Comment by lowyisan** [comment]
**Describe the work done in detail:**
The work for task involved documenting half of the class diagram comprehensively. This included specifying classes, their attributes, methods, and relationships for half of the diagram. The content was organised in a clear and coherent manner, making it easy for readers to understand.

**Has this work been committed to the repository?**
No, this task do not involve code changes. Therefore, no commits were made to the repository for this task.

**How does the work affect success or completion criteria?**
This work contributes to the success and completion of the task as it ensures that a significant part of the class diagram is well-documented, clear, and comprehensive. A well-documented class diagram is essential for understanding the structure of the software system and meets the criteria for a successful outcome.

**Start date and end date:**
Start Date: 24/10/23
End Date: 26/10/23

**Comment by ThJin** [comment]
**Describe the work done in detail.**
The work involved a comprehensive documentation effort focused on the class diagram representing the software system, ensuring that each component of the class diagram is thoroughly explained and logically organized.

**Has this work been committed to the repository?**
The work does not involve any code. Therefore, no repository commits is needed.

**How does the work affect success or completion criteria?**
The work ensures a clear and comprehensive documentation that accurately portrays the structure of the software system, ensuring a common understanding of the system's architecture.

Start date and end date:
[Start Date: 24/10/23]
[End Date: 26/10/23]
