### ISSUE TITLE
[2.1] Changes made from M1 Feedback

### ISSUE THREAD

**Issue by ImUrGit** [lowyisan/INF2001_P6-6#128]
What is the task about? This task is about revising and collating the changes the team has made after the M1 report has been reviewed.

What are the goals of the task? For Milestone 2, the task is to revise the changes and to come up with a few diagrams that will aid in explaining the system's architecture and workings. The following are diagrams that are to be completed:

- Component Diagram
- Class Diagram
- Sequence Diagram

Goals of the Task:

- Make changes based on feedback for M1 report.
- Identify areas for improvement in the system's design.
- Create 3 diagrams.

Success or Completion Criteria:

- All 3 diagrams to be completed
- Notable Improvements to be identified for completion in 2.2

Allocated time: 13 days

Start date and end date: [Start Date: 16/10/23], [End Date: 28/10/23]

Owner: All

Status of the task: To-Do

Priority: Medium

**Comment by mvchello** [comment]
**Describe the work done in detail.**
The team looked through the feedback given for M1 and split the work to tackle the needed changes.

**Has this work been committed to the repository?**
No work is needed to commit to the repository.

**How does the work affect success or completion criteria?**
It is important to know to make changes according to the M1 feedback as it corrects the team's direction as the project progresses.

**Start date and end date:**
[Start Date: 16/10/23]
[End Date: 28/10/23]

**Comment by Magic1sarap** [comment]
**Describe the work done in detail.**
The team revised the deliverables to follow suit to the feedback given for M1.

**Has this work been committed to the repository?**
No, as no code was required for this task. 

**How does the work affect success or completion criteria?**
The changes correct some of the mistakes made in M1 so as not to carry over the mistakes to M2. 

**Start date and end date:**
[Start Date: 16/10/23]
[End Date: 28/10/23]

**Comment by ImUrGit** [comment]
**Describe the work done in detail.**
I have helped to revise the feedback from the M1 feedback together with the team.

**Has this work been committed to the repository?**
There is no work that is needed to be pushed to the repository.

**How does the work affect success or completion criteria?**
The changes will directly affect the things that need to be created in the milestone 2 report.

**Start date and end date:**
[Start Date: 16/10/23]
[End Date: 28/10/23]

**Comment by ThJin** [comment]
**Describe the work done in detail.**
The work involved revising and consolidating changes made by the team after the review of the M1 report.

**Has this work been committed to the repository?**
The work does not involve any code. Therefore, no repository commits is needed.

**How does the work affect success or completion criteria?**
The work provides an improved M1 report based on the required changes based on feedback.

**Start date and end date:**
[Start Date: 16/10/23]
[End Date: 28/10/23]

**Comment by KeeHanXiang** [comment]
Describe the work done in detail.
The work involved revising changes after the review of the M1 report.

Has this work been committed to the repository?
The work does not involve any code. Therefore, no repository commits is needed.

How does the work affect success or completion criteria?
Improved sections from M1

Start date and end date:
[Start Date: 16/10/23]
[End Date: 28/10/23]

**Comment by lowyisan** [comment]
Describe the work done in detail:
For this task, I was responsible for revising and updating the Kanban board to reflect our progress and priorities accurately. I made the necessary changes based on the feedback we received after the M1 report review, ensuring that the board aligns with our current project status.

Has this work been committed to the repository?
The work does not involve any code. Therefore, no repository commits is needed.

How does the work affect success or completion criteria?
The Kanban board is a vital tool for tracking our project's progress and organizing tasks. By revising and updating it, we ensure that our project management remains efficient and aligns with the feedback received during the M1 review. This contributes to the overall success and completion of our Milestone 2 goals.

Start date and end date:
[Start Date: 16/10/23]
[End Date: 20/10/23]
