### ISSUE TITLE
[2.3.3.2] Component Diagram

### ISSUE THREAD

**Issue by ImUrGit** [lowyisan/INF2001_P6-6#132]
What is the task about? This task involves thoroughly documenting the component diagram that represents the software system based off the class diagram that  our teammates has done.

What are the goals of the task? The primary goal is to provide a component diagram together with the list of classess that reside in each component in the diagram.

Success or Completion Criteria: The task will be considered successful when a component diagram that shows the components of our system and a list of classes that reside in each component is presented.

Allocated time: 5 days

Start date and end date: [Start Date: 24/10/23], [End Date: 28/10/23]

Owner: Michelle & Alain

Status of the task: To-Do

Priority: Medium

**Comment by ImUrGit** [comment]
**Describe the work done in detail:** I have worked together with Michelle to document the component diagram into the M2 report and have done up some write ups and a table that lists down the classes that reside in the various components.

**Has this work been committed to the repository?** No, there is no need to commit this work to the repository as it is done on the project board.

**How does the work affect success or completion criteria?** The work done has made it easier for the people who are reading our report get a sense of how our system works and what are the components that our system has.

**Start Date:** 24/10/23, **End Date:** 28/10/23

**Comment by mvchello** [comment]
**Describe the work done in detail.**
Together with Alain, the components diagram has been drafted with reference to the overall class diagram. Furthermore, grouping of the BCE classes was done to determine the components and connection of the component diagram.

**Has this work been committed to the repository?**
No work is needed to commit to the repository.

**How does the work affect success or completion criteria?**
As it is needed to visually present the key components and their relationship with one another, the completion of this task is crucial for the furtherment of the project, setting a direction/wireframe for the team to follow.

**Start date and end date:**
[Start Date: 24/10/23]
[End Date: 28/10/23]
