### ISSUE TITLE
[2.3.3] Software Design

### ISSUE THREAD

**Issue by mvchello** [lowyisan/INF2001_P6-6#133]
What is the task about? This task involves documenting the description and justification of the product's design and concept rationale.

What are the goals of the task? The goal is to ensure that all if the software designs are well put together and that the design of the diagrams is justified.

Success or Completion Criteria: A justified software design provides a sound and extensive understanding of the system's functionality and how it interacts with users and each other, guiding the development of the product.

Allocated time: 5 days

Start date and end date: [Start Date: 24/10/23], [End Date: 28/10/23]

Owner: All

Status of the task: To-Do

Priority: Medium

**Comment by mvchello** [comment]
**Describe the work done in detail.**
Aided in the creation of the Component diagram. Helped to ensure the components aligned with the other diagrams that were created.

**Has this work been committed to the repository?**
No work is needed to commit to the repository.

**How does the work affect success or completion criteria?**
It is important to make such diagrams as it helps the team and clients to be on the same page regarding the structure of the product.

**Start date and end date:**
[Start Date: 24/10/23]
[End Date: 28/10/23]

**Comment by Magic1sarap** [comment]
**Describe the work done in detail.**
Have revised my sequence diagram for UC15 (Use Case 15: Manage new job assigned) after consultation to make 

**Has this work been committed to the repository?**
No work is needed to commit to the repository.

**How does the work affect success or completion criteria?**
It is important to know to make changes according to the M1 feedback as it corrects the team's direction as the project progresses.

**Start date and end date:**
[Start Date: 24/10/23]
[End Date: 28/10/23]

**Comment by ImUrGit** [comment]
**Describe the work done in detail.**
Together with Michelle, we have inserted the finalised component diagram into the Milestone 2 report. We have also added some write up to explain the classes in the various components.

**Has this work been committed to the repository?**
No work is needed to commit to the repository.

**How does the work affect success or completion criteria?**
It is important to document it as it is required in the Milestone 2 report deliverables.

**Start date and end date:**
[Start Date: 24/10/23]
[End Date: 28/10/23]

**Comment by ThJin** [comment]
**Describe the work done in detail.**
The work involved documenting the description and justification of the product's design. With the focus on detailing the software designs and providing clear justifications for the design choices made. 

**Has this work been committed to the repository?**
The work does not involve any code. Therefore, no repository commits is needed.

**How does the work affect success or completion criteria?**
The work ensures a well-documented and justified design on the development of the product, ensuring alignment with project goals.

Start date and end date:
[Start Date: 24/10/23]
[End Date: 28/10/23]

**Comment by KeeHanXiang** [comment]
Describe the work done in detail.
The work involved revision of the sequence diagram upon consultation and documenting the design.

Has this work been committed to the repository?
The work does not involve any code. Therefore, no repository commits is needed.

How does the work affect success or completion criteria?
The work ensures that the reader understands how and why the sequence diagram works that way.

Start date and end date:
[Start Date: 24/10/23]
[End Date: 28/10/23]

**Comment by lowyisan** [comment]
**Describe the work done in detail.**
The work involved documenting the class diagram and its descriptions to explain parts of it are well documented and explained.

**Has this work been committed to the repository?**
The work does not involve any code. Therefore, no repository commits is needed.

**How does the work affect success or completion criteria?**
The work ensures a well-documented class diagram, helping to make the software design clearer of the overall classes of the system.

**Start date and end date:**
[Start Date: 24/10/23]
[End Date: 28/10/23]
