### ISSUE TITLE
[2.3.3.3] Sequence Diagram

### ISSUE THREAD

**Issue by Magic1sarap** [lowyisan/INF2001_P6-6#134]
What is the task about? This task involves thoroughly documenting the sequence diagram that showcases the two most prominent use cases of the product.

What are the goals of the task? The primary goal is to provide a sequence diagram that accurately depicts the sequence flow of the the two most prominent use cases for the product..

Success or Completion Criteria: The task will be considered successful when the two sequence diagram aids the understanding of the used use case upon following through the diagram.

Allocated time: 5 days

Start date and end date: [Start Date: 24/10/23], [End Date: 28/10/23]

Owner: Han Xiang & Isaac

Status of the task: To-Do

Priority: Medium

**Comment by Magic1sarap** [comment]
**Describe the work done in detail.**
Have documented and added a description of the UC15 (Use Case 15: Manage new job assigned) for better interpretation of the sequence diagram.

**Has this work been committed to the repository?**
No, as no code was involved. 

**How does the work affect success or completion criteria?**
Provides clarity for the persons viewing the document including the stakeholders to understand the flow of the system better for this specific use case. 

**Start date and end date:**
[Start Date: 16/10/23]
[End Date: 28/10/23]

**Comment by KeeHanXiang** [comment]
Describe the work done in detail.
Have documented and added a description of the UC8 for better interpretation of the sequence diagram.

Has this work been committed to the repository?
No, as no code was involved.

How does the work affect success or completion criteria?
It explains the components used in the sequence diagram for better clarity.

Start date and end date:
[Start Date: 16/10/23]
[End Date: 28/10/23]
