### ISSUE TITLE
[3.5.2.1] Architecture Design

### ISSUE THREAD

**Issue by KeeHanXiang** [lowyisan/INF2001_P6-6#140]
**What is the task about?** 
This task is focused on drafting and describing the system's Architecture Design. 

**What are the goals of the task?** 
Successfully document the architecture design of the software. 

**Success or Completion Criteria:** 
Thoroughly document the architecture design, ensuring clarity, completeness and alignment with project requirements.

**Allocated time:** 4 days

**Start date and end date:** [Start Date: 09/11/23], [End Date: 12/11/23]

**Owner:** Han Xiang & Jin Hao

**Status of the task:** To-Do

**Priority:** High

**Comment by KeeHanXiang** [comment]
Describe the work done in detail.
The task involves creating a detailed Architecture Design for the software, including planning, design, clarity, completeness, and alignment with requirements.

Has this work been committed to the repository?
The work does not involve any code. Therefore, no repository commits is needed.

How does the work affect success or completion criteria?
Successful completion of this task significantly affects meeting the completion criteria, which includes thorough and clear documentation of the architecture design aligned with project requirements.

Start date and end date:
[Start Date: 09/11/23]
[End Date: 12/11/23]

**Comment by ThJin** [comment]
**Describe the work done in detail.**
The work involved in documenting the architecture design of the software.

**Has this work been committed to the repository?**
The work does not involve any code. Therefore, no repository commits is needed.

**How does the work affect success or completion criteria?**
The work ensures that by providing a clear and comprehensive documentation it ensures clarity.

Start date and end date:
[Start Date: 09/11/23]
[End Date: 12/11/23]
