### ISSUE TITLE
[3.2.1] Creation of Architecture Design

### ISSUE THREAD

**Issue by KeeHanXiang** [lowyisan/INF2001_P6-6#144]
**What is the task about?** 
This task is focused on documenting the Architecture Design.

**What are the goals of the task?** 
Ensure that the Architecture Design has been implemented and documented properly. 

**Success or Completion Criteria:** 
Provide well-documented and up-to-date Architecture Design. 

**Allocated time:** 3 days

**Start date and end date:** [Start Date: 09/11/23], [End Date: 11/11/23]

**Owner:** Han Xiang & Jin Hao

**Status of the task:** To-Do

**Priority:** High

**Comment by KeeHanXiang** [comment]
Describe the work done in detail.
This task focuses on documenting the Architecture Design, ensuring it is correctly implemented.

Has this work been committed to the repository?
The work does not involve any code. Therefore, no repository commits is needed.

How does the work affect success or completion criteria?
Successfully documenting the Architecture Design is essential to meeting the completion criteria, which requires well-documented and up-to-date design documentation.

Start date and end date:
[Start Date: 09/11/23]
[End Date: 11/11/23]

**Comment by ThJin** [comment]
**Describe the work done in detail.**
The work involved documenting the architecture design, ensuring that its implemented and documented correctly.

**Has this work been committed to the repository?**
The work does not involve any code. Therefore, no repository commits is needed.

**How does the work affect success or completion criteria?**
The work ensures that a comprehensive documentation will help in guiding the development.

Start date and end date:
[Start Date: 09/11/23]
[End Date: 11/11/23]
