### ISSUE TITLE
[3.2.2] Creation of Detailed Design

### ISSUE THREAD

**Issue by KeeHanXiang** [lowyisan/INF2001_P6-6#145]
**What is the task about?** 
This task is focused on documenting the Detailed Design.

**What are the goals of the task?** 
Ensure that the Detailed Design has been implemented and documented properly. 

**Success or Completion Criteria:** 
Provide well-documented and up-to-date Detailed Design. 

**Allocated time:** 3 days

**Start date and end date:** [Start Date: 11/11/23], [End Date: 13/11/23]

**Owner:** Han Xiang & Jin Hao

**Status of the task:** To-Do

**Priority:** High

**Comment by KeeHanXiang** [comment]
Describe the work done in detail.
This task involves documenting the Detailed Design to ensure its accurate implementation.

Has this work been committed to the repository?
The work does not involve any code. Therefore, no repository commits is needed.

How does the work affect success or completion criteria?
Successfully documenting the Detailed Design is essential for meeting the completion criteria, which demands well-documented and up-to-date design documentation.

Start date and end date:
[Start Date: 11/11/23]
[End Date: 13/11/23]

**Comment by ThJin** [comment]
**Describe the work done in detail.**
The work involved in making sure the detailed design has been implemented and documented accurately. 

**Has this work been committed to the repository?**
The work does not involve any code. Therefore, no repository commits is needed.

**How does the work affect success or completion criteria?**
The work ensures a comprehensive documentation will aid in providing clear details on the system's specifications.

Start date and end date:
[Start Date: 11/11/23]
[End Date: 13/11/23]
