### ISSUE TITLE
[3.2.2.1] Review of Class Diagram

### ISSUE THREAD

**Issue by KeeHanXiang** [lowyisan/INF2001_P6-6#146]
**What is the task about?** 
This task involves revising the existing class diagram for the project to reflect any changes or improvements in the system's design and object-oriented structure.

**What are the goals of the task?** 
The goal is to update the class diagram to accurately represent the current design, ensuring alignment with system requirements, and validating the correctness of class relationships and attributes.

**Success or completion criteria:** 
Successful completion of this task means that the revised class diagram has been reviewed and approved by the project team.

**Allocated time:** 3 days

**Start date and end date:** [Start Date: 11/11/23], [End Date: 13/11/23]

**Owner:** Michelle & Han Xiang

**Status of the task:** To-Do

**Priority:** High

**Comment by KeeHanXiang** [comment]
**Describe the work done in detail.**
This task involves revising the existing class diagram to align it with the current system design, validate class relationships and attributes, and ensure compliance with system requirements.

**Has this work been committed to the repository?**
The work does not involve any code. Therefore, no repository commits is needed.

**How does the work affect success or completion criteria?**
Successful completion means that the project team has reviewed and approved the revised class diagram, confirming its accuracy.

**Start date and end date:**
[Start Date: 11/11/23]
[End Date: 13/11/23]

**Comment by mvchello** [comment]
**Describe the work done in detail.**
The task entails a comprehensive review of the current class diagram to harmonize it with the latest system design. This includes verifying class relationships and attributes, ensuring that they align with system requirements and accurately represent the system's structure.

**Has this work been committed to the repository?**
The work does not involve any code. Therefore, no repository commits is needed.

**How does the work affect success or completion criteria?**
Successful execution of this task hinges on the team's ability to integrate whatever that has been reviewed into the wireframe prototype.

**Start date and end date:**
[Start Date: 11/11/23]
[End Date: 13/11/23]
