### ISSUE TITLE
[3.2.2.2] Creation of Observer Pattern Diagram

### ISSUE THREAD

**Issue by KeeHanXiang** [lowyisan/INF2001_P6-6#147]
**What is the task about?** 
This task is focused on documenting the Observer Pattern Diagram.

**What are the goals of the task?** 
Ensure that the Observer Pattern Diagram has been done and documented properly. 

**Success or Completion Criteria:** 
Provide well-documented and up-to-date Observer Pattern Diagram. 

**Allocated time:** 3 days

**Start date and end date:** [Start Date: 13/11/23], [End Date: 15/11/23]

**Owner:** Han Xiang & Jin Hao

**Status of the task:** To-Do

**Priority:** High

**Comment by KeeHanXiang** [comment]
Describe the work done in detail.
This task involves creating and documenting the Observer Pattern Diagram to accurately represent its usage in the project.

Has this work been committed to the repository?
The work does not involve any code. Therefore, no repository commits is needed.

How does the work affect success or completion criteria?
Successfully completing this task ensures that a well-documented and up-to-date Observer Pattern Diagram is available.

Start date and end date:
[Start Date: 13/11/23]
[End Date: 15/11/23]

**Comment by ThJin** [comment]
**Describe the work done in detail.**
The work involved in creating and documenting the observer pattern diagram accurately.

**Has this work been committed to the repository?**
The work does not involve any code. Therefore, no repository commits is needed.

**How does the work affect success or completion criteria?**
The work ensures a well documented and up-to-date observer pattern diagram help in contributing to the project success.

Start date and end date:
[Start Date: 13/11/23]
[End Date: 15/11/23]
