### ISSUE TITLE
[3.5] Documentation

### ISSUE THREAD

**Issue by KeeHanXiang** [lowyisan/INF2001_P6-6#148]
**What is the task about?** 
This task is focused on Documentation.

**What are the goals of the task?** 
Successfully update or create documentation related to M3. 

**Success or Completion Criteria:** 
Ensure all relevant documentation is accurate, up-to-date, and aligns with the implemented design. 

**Allocated time:** 17 days

**Start date and end date:** [Start Date: 09/11/23], [End Date: 25/11/23]

**Owner:** All

**Status of the task:** To-Do

**Priority:** High

**Comment by KeeHanXiang** [comment]
Describe the work done in detail.
This task involves updating or creating documentation related to M3 to ensure accuracy and alignment with the implemented design.

Has this work been committed to the repository?
The work does not involve any code. Therefore, no repository commits is needed.

How does the work affect success or completion criteria?
Successfully completing this task ensures that all relevant documentation related to M3 is accurate, up-to-date, and in line with the implemented design.

Start date and end date:
[Start Date: 09/11/23]
[End Date: 25/11/23]

**Comment by lowyisan** [comment]
**Describe the work done in detail.**
My contributions to the Documentation task for M3 included two key components: drafting the References and Acknowledgement section and documenting the White Box testing process.

**Has this work been committed to the repository?**
The work does not involve any code. Therefore, no repository commits is needed.

**How does the work affect success or completion criteria?**
The completion of these documentation tasks is critical for the success of our M3 milestone. The References and Acknowledgement section adds credibility and integrity to our document, while the White Box testing documentation ensures that our internal testing processes are transparent and can be reviewed or audited in the future. Together, they ensure that our documentation aligns with the implemented design and meets our project standards.

**Start date and end date:**
[Start Date: 09/11/23]
[End Date: 19/11/23]

**Comment by ImUrGit** [comment]
Describe the work done in detail.
I have worked on the documentation in a few tasks like for example: doing up the layered software architecture diagram and helped in the the pattern design.

Has this work been committed to the repository?
The work does not involve any code. Therefore, no repository commits is needed.

How does the work affect success or completion criteria?
It is important to do the tasks delegated to us to ensure that we can deliver the documentation in time.

Start date and end date:
[Start Date: 09/11/23]
[End Date: 25/11/23]

**Comment by Magic1sarap** [comment]
**Describe the work done in detail.**
I have worked on the documentation of the project prototypes and its descriptions, likening it to the respective PFs and FRs. 

**Has this work been committed to the repository?**
The work does not involve any code. Therefore, no repository commits is needed.

**How does the work affect success or completion criteria?**
Provides a good description in detail and wording of the prototypes functionalities instead of just looking at the UI. 

Start date and end date:
[Start Date: 09/11/23]
[End Date: 25/11/23]

**Comment by mvchello** [comment]
**Describe the work done in detail.**
Worked on the documentation, primarily the project prototype and wireframe section. 

**Has this work been committed to the repository?**
The work does not involve any code. Therefore, no repository commits is needed.

**How does the work affect success or completion criteria?**
It is important to do so as it gives a visual and literate representation of the team's product.

Start date and end date:
[Start Date: 09/11/23]
[End Date: 25/11/23]

**Comment by ThJin** [comment]
**Describe the work done in detail.**
The work involved documentation to convey the details of M3. Ensuring that that all information is accurately represented.

**Has this work been committed to the repository?**
The work does not involve any code. Therefore, no repository commits is needed.

**How does the work affect success or completion criteria?**
The work ensures that by achieving accurate, up-to-date documentation will aligns with the implementation design of M3.

Start date and end date:
[Start Date: 09/11/23]
[End Date: 25/11/23]
