### ISSUE TITLE
[3.5.1] Introduction

### ISSUE THREAD

**Issue by lowyisan** [lowyisan/INF2001_P6-6#151]
**What is the task about?** 
This task is focused on drafting the introduction for the documentation. 

**What are the goals of the task?** 
Create the introduction segment for the M3 report. 

**Success or Completion Criteria:** 
Completion of a comprehensive project introduction write up.

**Allocated time:** 1 day

**Start date and end date:** [Start Date: 09/11/23], [End Date: 09/11/23]

**Owner:** Alain & Yi San

**Status of the task:** To-Do

**Priority:** High

**Comment by lowyisan** [comment]
**Describe the work done in detail.**
I focused on outlining the scope and objectives of our project in the introduction for the M3 report. My contribution involved detailing the project's background, its rationale, and setting the expectations for the rest of the document. I also included a brief overview of the progress made to date, linking it to the objectives we set out in the initial phases of the project.

**Has this work been committed to the repository?**
The work does not involve any code. Therefore, no repository commits is needed.

**How does the work affect success or completion criteria?**
The work I've done lays down a solid foundation for the introduction section of our M3 report. It addresses half of the completion criteria for a comprehensive project introduction and sets the stage for Alain's addition to complete the segment.


**Start date and end date:**
[Start Date: 09/11/23]
[End Date: 09/11/23]

**Comment by ImUrGit** [comment]
Describe the work done in detail.
Worked on the introduction of the project and helped in outlining the scope and objectives of the project. I have also checked through together with Yi San on the project's background and the rationale behind the documentation.

Has this work been committed to the repository?
The work does not involve any code. Therefore, no repository commits is needed.

How does the work affect success or completion criteria?
The introduction sets the tone of the whole documentation, it is important to start with a good introduction so as to prepare readers what they are about to read.

Start date and end date:
[Start Date: 09/11/23]
[End Date: 09/11/23]
