### ISSUE TITLE
[3.4.1] Reviewed Client Requirements

### ISSUE THREAD

**Issue by lowyisan** [lowyisan/INF2001_P6-6#158]
**What is the task about?** 
This task is focused on reviewing client requirements to ensure that our implementation follows those requirements.

**What are the goals of the task?** 
Successfully review and validated client requirements for accuracy and completeness. 

**Success or Completion Criteria:** 
Complete a thorough review of client requirements, address any identified discrepancies, and ensure alignment with project objectives. 

**Allocated time:** 2 days

**Start date and end date:** [Start Date: 14/11/23], [End Date: 15/11/23]

**Owner:** Alain & Yi San

**Status of the task:** To-Do

**Priority:** High

**Comment by lowyisan** [comment]
**Describe the work done in detail.**
I have meticulously reviewed and cross-validated our project's implementation against the client's requirements. This involved a screen-by-screen comparison to ensure that every client specification has been met or accounted for within our software. Each requirement was checked for accuracy and completeness in alignment with the functionalities we have implemented.

**Has this work been committed to the repository?**
The work does not involve any code. Therefore, no repository commits is needed.

**How does the work affect success or completion criteria?**
The successful review of the client's requirements is crucial to the project's overall success. It ensures that we are on track to meet the project's objectives and that the final product will satisfy the client's needs. Addressing any discrepancies identified during the review process is vital for maintaining the integrity of our software and for upholding the quality standards expected by the client.

**Start date and end date:****
[Start Date: 14/11/23]
[End Date: 15/11/23]

**Comment by lowyisan** [comment]
-

**Comment by ImUrGit** [comment]
Describe the work done in detail.
Worked on ensuring the document and the system aligns with what our client wants. I have also helped in making sure that the functional requirements conveyed by the client is implemented into our project.

Has this work been committed to the repository?
The work does not involve any code. Therefore, no repository commits is needed.

How does the work affect success or completion criteria?
It is important for us to continually make sure that whatever we do, be it in the documentation or in the system will be aligned towards what our clients want. At the end of the day, we are working for the client and we want to make sure that we deliver.

Start date and end date:
[Start Date: 14/11/23]
[End Date: 15/11/23]
