### ISSUE TITLE
[3.2] Creation of Software Design

### ISSUE THREAD

**Issue by ImUrGit** [lowyisan/INF2001_P6-6#161]
**What is the task about?** 
This task is focused on documenting supplementary system designs which include the Architecture Design as well as the Detailed Design. 

**What are the goals of the task?** 
Ensure that all relevant supplementary system designs are documented comprehensively.

**Success or Completion Criteria:** 
Provide well-documented and up-to-date supplementary system designs, addressing the specific areas of concern.

**Allocated time:** 9 days

**Start date and end date:** [Start Date: 09/11/23], [End Date: 17/11/23]

**Owner:** Alain & Jin Hao

**Status of the task:** To-Do

**Priority:** High

**Comment by ImUrGit** [comment]
Describe the work done in detail.
Worked on doing the software architecture design that we have chosen which is a layered software architecture design. Did up a software architecture diagram as well to illustrate layering.

Has this work been committed to the repository?
The work does not involve any code. Therefore, no repository commits is needed.

How does the work affect success or completion criteria?
The documentation of the Software Architecture Diagram and Detailed Design Patterns i important because when the team is to code on this system, it is important for the development process.

Start date and end date:
[Start Date: 09/11/23]
[End Date: 17/11/23]

**Comment by ThJin** [comment]
**Describe the work done in detail.**
The work involved in providing a comprehensive and up-to-date documentation of the supplementary system designs.

**Has this work been committed to the repository?**
The work does not involve any code. Therefore, no repository commits is needed.

**How does the work affect success or completion criteria?**
The work ensures that by providing well-documented and up-to-date documentation will aid in effective and communication in development process.

Start date and end date:
[Start Date: 09/11/23]
[End Date: 17/11/23]
