### ISSUE TITLE
[3.5.2] Software Design

### ISSUE THREAD

**Issue by ImUrGit** [lowyisan/INF2001_P6-6#162]
**What is the task about?** 
This task is focused on drafting and describing the system's Software Design. 

**What are the goals of the task?** 
Successfully document the implemented software design.

**Success or Completion Criteria:** 
Completion of comprehensive software design documentation, ensuring clarity, completeness, and alignment with the implemented design. 

**Allocated time:** 8 days

**Start date and end date:** [Start Date: 09/11/23], [End Date: 16/11/23]

**Owner:** Alain & Jin Hao

**Status of the task:** To-Do

**Priority:** High

**Comment by ImUrGit** [comment]
Describe the work done in detail.
I have worked on the documentation of the software architecture diagram that our team has chosen which is the layered software architecture diagram. I have also done up a diagram to illustrate how the architecture is implemented into our system.

Has this work been committed to the repository?
The work does not involve any code. Therefore, no repository commits is needed.

How does the work affect success or completion criteria?
The documentation of the software architecture diagram is important to let the readers know the effects of implementing the layered software architecture diagram.

Start date and end date:
[Start Date: 09/11/23]
[End Date: 16/11/23]

**Comment by ThJin** [comment]
**Describe the work done in detail.**
The work involved in documenting the implemented software design.

**Has this work been committed to the repository?**
The work does not involve any code. Therefore, no repository commits is needed.

**How does the work affect success or completion criteria?**
The work ensures that a comprehensive software design documentation will aid in providing clarity.

Start date and end date:
[Start Date: 09/11/23]
[End Date: 16/11/23]
