### ISSUE TITLE
[3.4] Created Project Prototype & Wireframes

### ISSUE THREAD

**Issue by Magic1sarap** [lowyisan/INF2001_P6-6#164]
**What is the task about?** 
This task is focused on creating the Project Prototype & Wireframes.

**What are the goals of the task?** 
Successfully develop the project prototype and wireframes based on the design specifications.

**Success or Completion Criteria:** 
Create a comprehensive project prototype and wireframes, ensuring alignment with design specifications and obtaining stakeholder approval. 

**Allocated time:** 3 days

**Start date and end date:** [Start Date: 14/11/23], [End Date: 20/11/23]

**Owner:** Isaac & Michelle

**Status of the task:** To-Do

**Priority:** High

**Comment by Magic1sarap** [comment]
**Describe the work done in detail.**
Created the project prototype and wireframes for the M3 deliverable.

**Has this work been committed to the repository?**
The work does not involve any code. Therefore, no repository commits is needed.

**How does the work affect success or completion criteria?**
The completion of the prototype forms a tangible product of the requirements into an actual software that can be interacted with, essential for realisation. 

Start date and end date:
[Start Date: 14/11/23]
[End Date: 20/11/23]

**Comment by mvchello** [comment]
**Describe the work done in detail.**
The work primarily entailed the creation of the project prototype and wireframes specifically for the M3 deliverable. These prototypes serve as visual representations and mockups of the software's user interface and functionality.

**Has this work been committed to the repository?**
The work does not involve any code. Therefore, no repository commits is needed.

**How does the work affect success or completion criteria?**
The completion of the prototype is a significant milestone as it transforms the project requirements into a tangible software product that can be interacted with. This step is crucial for realizing the project's objectives and ensuring that it aligns with the intended functionality.

Start date and end date:
[Start Date: 14/11/23]
[End Date: 20/11/23]
