### ISSUE TITLE
[3.4.3] Creation of Project Prototype

### ISSUE THREAD

**Issue by Magic1sarap** [lowyisan/INF2001_P6-6#165]
**What is the task about?** 
This task is focused on the creation of the Project Prototype.

**What are the goals of the task?** 
Successfully develop and finalise the Project Prototype.

**Success or Completion Criteria:** 
Achieve completion of the Project prototype, addressing all planned functionalities as well as design elements to complement it.

**Allocated time:** 5 days

**Start date and end date:** [Start Date: 16/11/23], [End Date: 20/11/23]

**Owner:** Isaac & Michelle

**Status of the task:** To-Do

**Priority:** High

**Comment by Magic1sarap** [comment]
**Describe the work done in detail.**
Used Figma for the creation of the implemented prototype. 

**Has this work been committed to the repository?**
The work does not involve any code. Therefore, no repository commits is needed.

**How does the work affect success or completion criteria?**
Allows stakeholders to interact with a tangible product that aim to meet their real-world requirements. 

Start date and end date:
[Start Date: 16/11/23]
[End Date: 20/11/23]

**Comment by mvchello** [comment]
**Describe the work done in detail.**
Used Figma for the creation of the implemented prototype. 

**Has this work been committed to the repository?**
The work does not involve any code. Therefore, no repository commits is needed.

**How does the work affect success or completion criteria?**
This work facilitates stakeholder engagement with a concrete product, aligning it with their real-world needs and expectations. It plays a pivotal role in ensuring the project's success and meeting the established criteria for completion.

Start date and end date:
[Start Date: 16/11/23]
[End Date: 20/11/23]
