### ISSUE TITLE
[3.5.5] Project Management

### ISSUE THREAD

**Issue by Magic1sarap** [lowyisan/INF2001_P6-6#167]
**What is the task about?** 
This task is focused on the documentation of Project Management. 

**What are the goals of the task?** 
Successfully compile and document key aspects of project management, including processes, timelines and milestones. 

**Success or Completion Criteria:** 
Complete the documentation of project management processes, timelines, and milestones, ensuring clarity and accuracy. 

**Allocated time:** 4 days

**Start date and end date:** [Start Date: 22/11/23], [End Date: 25/11/23]

**Owner:** Isaac & Michelle

**Status of the task:** To-Do

**Priority:** High

**Comment by Magic1sarap** [comment]
**Describe the work done in detail.**
I thoroughly documented key aspects of project management, concentrating on compiling details related to processes, timelines and milestones. The goal was to ensure a comprehensive and accurate representation of project management components. 

**Has this work been committed to the repository?**
The work does not involve any code. Therefore, no repository commits is needed.

**How does the work affect success or completion criteria?**
The documentation work aimed at achieving the success criteria by completing comprehensive documentation of project management processes, timelines, and milestones. 

**Start date and end date:**
[Start Date: 22/11/23]
[End Date: 25/11/23]

**Comment by mvchello** [comment]
**Describe the work done in detail.**
The work involved a thorough documentation effort focused on critical aspects of project management. This effort concentrated on gathering and organizing information related to processes, timelines, and milestones, with the overarching objective of creating a comprehensive and accurate representation of these key project management components.

**Has this work been committed to the repository?**
The work does not involve any code. Therefore, no repository commits is needed.

**How does the work affect success or completion criteria?**
The documentation work was instrumental in achieving the success criteria by producing comprehensive documentation pertaining to project management processes, timelines, and milestones. This documentation is vital for ensuring that the project aligns effectively with its completion criteria.

**Start date and end date:**
[Start Date: 22/11/23]
[End Date: 25/11/23]
