### ISSUE TITLE
[1.1.2] Project Research

### ISSUE THREAD

**Issue by mvchello** [lowyisan/INF2001_P6-6#26]
**Task title ID:** #07

**What is the task about?** This task involves conducting research related to the project, including current solutions in the market, research on workload management strategies, and research on the aircon retailer industry.

**What are the goals of the task?**  The goals include gathering valuable insights, data, and information for project planning and decision-making.

**Success or completion criteria:** Successful completion of this task involves the compilation of relevant research findings and their applicability to the project.

**Allocated time:** 5 days

**Start date and end date:** [Start Date: 31/08/23], [End Date: 04/09/23]

**Owner:** Isaac & Michelle

**Status of the task:** To-Do

**Priority:** High

**Comment by Magic1sarap** [comment]
**Describe the work done in detail:**
Have conducted research heavily on related systems utilising workload management systems or scheduling systems that require large sums of human resource. 

**Has this work been committed to the repository?**
No, as there was no code involved. 

**How does the work affect success or completion criteria?**
Provides substantial evidence of research done towards the project making it a more reliable and reputable document/project. 

Start date and end date:
Start Date: 31/08/23
End Date: 04/09/23

**Comment by mvchello** [comment]
**Describe the work done in detail:**
Researched how the Aircon Retailer Industry works, the mechanics behind their workload management system, and the different requirements for each work allocation. Moreover, research on current solutions that are in place for workload management systems was also carried out.

**Has this work been committed to the repository?**
No, as there was no code involved. 

**How does the work affect success or completion criteria?**
Provides substantial evidence of research done towards the project making it a more reliable and valid project. 

Start date and end date:
Start Date: 31/08/23
End Date: 04/09/23
