### ISSUE TITLE
[1.4.3] Specific Requirements

### ISSUE THREAD

**Issue by lowyisan** [lowyisan/INF2001_P6-6#35]
**Task title ID:** #34

**What is the task about?** To document all project requirements, including user interface requirements, functional requirements, use case model, non functional requirements, and any other relevant requirements to provide a comprehensive and detailed specification for the project. 

**What are the goals of the task?** The goal of this task is to compile a set of specific project requirements, including user interface, functional, use case, non-functional, and other requirements to serve as a foundation for project development and ensure alignment with client needs. 

**Success or completion criteria:** This task is considered successful when it results in a well-documented and validated set of requirements that accurately reflect client needs and expectations, providing a clear and detailed project specification for development and future testing. 

**Allocated time:** 6 days

**Start date and end date:** [Start Date: 11/09/23], [End Date: 16/09/23]

**Owner:** Alain & Yi San

**Status of the task:** To-Do

**Priority:** High

**Comment by lowyisan** [comment]
**Describe the work done in detail:**
In this task, we documented the specific requirements for the workload allocation system. This included gathering and analyzing the client's requirements, refining them for clarity and completeness, and documenting them in a detailed and organized manner.

**Has this work been committed to the repository?**
No, this task does not involve code changes. Therefore, no commits were made to the repository for this task.

**How does the work affect success or completion criteria?**
Documenting specific requirements is a critical step in the project's success as it provides a clear and agreed-upon foundation for the development process. It aligns with the completion criteria by ensuring that all requirements are well-defined and traceable.

Start date and end date:
Start Date: 11/09/23
End Date: 16/09/23

**Comment by ImUrGit** [comment]
**Describe the work done in detail:**
In this task, I have helped in documenting the specific requirements for the workload allocation system. This would include gathering and analyzing the client's requirements, refining them for clarity and completeness, and documenting them in a detailed and organized manner.

**Has this work been committed to the repository?**
No, this task do not involve code changes. Therefore, no commits were made to the repository for this task.

**How does the work affect success or completion criteria?**
It is important to document the things we agree on with the client so as to help us in putting things in black and white. This will make it easier for the team and the client in keeping track oh what is understood between us.

Start date and end date:
Start Date: 11/09/23
End Date: 16/09/23
