### ISSUE TITLE
[1.4] Documentation

### ISSUE THREAD

**Issue by lowyisan** [lowyisan/INF2001_P6-6#39]
**Task title ID:** #27

**What is the task about?** This task records the information that is integral to the product. 

**What are the goals of the task?** This task seeks to capture, organize, and showcase information needed for the product effectively. 

**Success or completion criteria:** The success of the task depends on readers being able to understand the product, its scope, and the measures to finish the project.

**Allocated time:** 13 days

**Start date and end date:** [Start Date: 11/09/23], [End Date: 23/09/23]

**Owner:** All

**Status of the task:** To-Do

**Priority:** High

**Comment by lowyisan** [comment]
**Describe the work done in detail:**
The work done consists of improving on the current requirements and documenting some of the functional and non functional requirements based on the client's input.

**Has this work been committed to the repository?**
No, this task do not involve code changes. Therefore, no commits were made to the repository for this task.

**How does the work affect success or completion criteria?**
This work helps to contribute towards the completion of the requirements for the stakeholders to gain a better understanding of the solution to be developed by reading the document

Start date and end date:
Start Date: 11/09/23
End Date: 23/09/23

**Comment by Magic1sarap** [comment]
**Describe the work done in detail:**
The work includes the documentation and crafting of certain functional and non-functional requirements, as well as the need for other requirements towards the project needs based on client feedback. 

**Has this work been committed to the repository?**
Task does not involve code therefore no repository commits.

**How does the work affect success or completion criteria?**
This work helps to contribute towards the completion of the requirements for the stakeholders to gain a better understanding of the solution to be developed by reading the document

Start date and end date:
Start Date: 11/09/23
End Date: 23/09/23

**Comment by mvchello** [comment]
**Describe the work done in detail:**
Documenting what has been done in the project so far. Main sections worked on: Introduction and Project Estimation & Plan.

**Has this work been committed to the repository?**
No, as there was no code involved. 

**How does the work affect success or completion criteria?**
Completion of the work contributes to the success of the project as documentation is needed for stakeholders to understand the product better,

Start date and end date:
Start Date: 11/08/23
End Date: 23/09/23

**Comment by mvchello** [comment]
.

**Comment by KeeHanXiang** [comment]
Describe the work done in detail:
The work involves documenting completed tasks in the report.

Has this work been committed to the repository?
No, this task does not involve code changes. Therefore, no commits were made to the repository for this task.

How does the work affect success or completion criteria?
It allows the client to understand our project and estimations as well as what to expect.

Start date and end date:
Start Date: 11/09/23
End Date: 23/09/23

**Comment by ThJin** [comment]
Describe the work done in detail.
The work involved included writing down essential information that is crucial to the end product. The information must be gathered, arranged, and presented in a way that conveys the specifics of the product.

Has this work been committed to the repository?
The work does not involve any code. Therefore, no repository commits is needed.

How does the work affect success or completion criteria?
The work ensures that readers can understand the product, its scope, and measures required to complete the project.

Start date and end date:
[Start Date: 11/09/23]
[End Date: 23/09/23]

**Comment by ImUrGit** [comment]
Describe the work done in detail.
The work involved includes documenting the essential informations that we want to convey to the client such as the function and nonfunctional requirements.

Has this work been committed to the repository?
The work does not involve any code. Therefore, no repository commits is needed.

How does the work affect success or completion criteria?
It is important to document down whatever that we have agreed on with the client so as to ensure that the team and the client is on the same page.

Start date and end date:
[Start Date: 11/09/23]
[End Date: 23/09/23]
