### ISSUE TITLE
[1.4.4] Project Estimation & Plan

### ISSUE THREAD

**Issue by ImUrGit** [lowyisan/INF2001_P6-6#50]
**Task title ID:** #40

**What is the task about?** Create a detailed project estimation and plan, including scope, timelines, resource allocation to provide a roadmap for successful project execution.

**What are the goals of the task?** The goal is to establish a comprehensive project plan that outlines the project's scope, schedule, resource requirements as well as project constraints. 

**Success or completion criteria:** Successful completion involves having a well-defined project plan that aligns with project objectives, is within the project constraints as well as a clear roadmap for the project execution. 

**Allocated time:** 8 days

**Start date and end date:** [Start Date: 16/09/23], [End Date: 21/09/23]

**Owner:** All

**Status of the task:** To-Do

**Priority:** High

**Comment by lowyisan** [comment]
**Describe the work done in detail:**
The work done includes the calculation of the effort estimation based on the Use Case Points calculated under size estimation.

**Has this work been committed to the repository?**
No, this task do not involve code changes. Therefore, no commits were made to the repository for this task.

**How does the work affect success or completion criteria?**
The documentation of the effort estimation is crucial for our team to ensure that the product can be developed on time.

Start date and end date:
Start Date: 16/09/23
End Date: 21/09/23

**Comment by Magic1sarap** [comment]
**Describe the work done in detail:**
The work done involves prediction of effort costs based on the use cases.

**Has this work been committed to the repository?**
No code was involved in this task, thus no commits to the repository. 

**How does the work affect success or completion criteria?**
The predictions and estimate calculations are necessary to provide logical time boundaries to not overshoot the timelines that we have to work within. 

Start date and end date:
Start Date: 16/09/23
End Date: 21/09/23

**Comment by mvchello** [comment]
**Describe the work done in detail:**
Contributed to the estimation and planning of the project in order to gauge the time, and effort needed to be put into the project. Additionally, helped to manage the project through the creation of tools such as Work Breakdown Structure and Gantt chart in order to keep track of the progress of the project.

**Has this work been committed to the repository?**
No, as there was no code involved. 

**How does the work affect success or completion criteria?**
The work donee ensures that the project is progressing in the right direction within the timeframe that has been laid out beforehand.

Start date and end date:
Start Date: 16/09/23
End Date: 21/09/23

**Comment by mvchello** [comment]
.

**Comment by KeeHanXiang** [comment]
**Describe the work done in detail:**
The work involved defining the project's scope, creating a detailed timeline, allocating resources, and considering project constraints. 

**Has this work been committed to the repository?**
No, as there was no code involved.

**How does the work affect success or completion criteria?**
The work done provides the team a timeline to follow.

Start date and end date:
Start Date: 16/09/23
End Date: 21/09/23

**Comment by ThJin** [comment]
Describe the work done in detail.
The work involved creating a detailed project estimation and plan. That provides a comprehensive roadmap for the successful execution of the project.

Has this work been committed to the repository?
The work does not involve any code. Therefore, no repository commits is needed.

How does the work affect success or completion criteria?
The work provides a clear roadmap for executing the project successfully while guaranteeing consistency with its goals.

Start date and end date:
[Start Date: 16/09/23]
[End Date: 21/09/23]

**Comment by ImUrGit** [comment]
Describe the work done in detail.
The work involved includes doing the size, effort and duraiton estimation of the project. We have also discussed on what SDLC methodology we are adopting as a team.

Has this work been committed to the repository?
The work does not involve any code. Therefore, no repository commits is needed.

How does the work affect success or completion criteria?
It is important to estimate the size of our project and what we have to do so as to ensure a smooth payment process with the client later on.

Start date and end date:
[Start Date: 16/09/23]
[End Date: 21/09/23]
