### ISSUE TITLE
[1.4.4.1] Software Estimation

### ISSUE THREAD

**Issue by ImUrGit** [lowyisan/INF2001_P6-6#51]
**Task title ID:** #41

**What is the task about?** Estimate the time, effort, resources required for the software development project, considering scope, complexity as well as team capabilities to create an accurate project plan. 

**What are the goals of the task?** The goal of this task is to provide accurate and realistic estimates for project planning and resource allocation.

**Success or completion criteria:** Successful completion of this task involves: 

1. Size Estimation
2. Effort Estimation
3. Duration Estimation

**Allocated time:** 5 days

**Start date and end date:** [Start Date: 17/09/23], [End Date: 21/09/23]

**Owner:** All

**Status of the task:** Completed

**Priority:** High

**Comment by ImUrGit** [comment]
**Describe the work done in detail.**
The team has completed in providing estimates of the project such as the size, effort and duration estimations. 

**Has this work been committed to the repository?**
No work is needed to commit to the repository.

**How does the work affect success or completion criteria?**
It is important to correctly estimate the project's size, effort and duration so as to be able to communicate with the client for updates, information and payment.

**Start date and end date:**
[Start Date: 17/09/23]
[End Date: 21/09/23]

**Comment by lowyisan** [comment]
**Describe the work done in detail.**
The work done includes calculating the efforts estimation to document into our M1.

**Has this work been committed to the repository?**
No work is needed to commit to the repository.

**How does the work affect success or completion criteria?**
This helps all stakeholders understand the size of effort based off the UCP calculated beforehand.

**Start date and end date:**
[Start Date: 17/09/23]
[End Date: 21/09/23]

**Comment by Magic1sarap** [comment]
**Describe the work done in detail.**
The work done includes the prediction as well as estimation of the time and effort required in completing the software solution. 

**Has this work been committed to the repository?**
No, as this does not involve any code changes. 

**How does the work affect success or completion criteria?**
This provides a clearer picture of the size and effort towards completion of the project. 

Start date and end date:
[Start Date: 17/09/23]
[End Date: 21/09/23]

**Comment by mvchello** [comment]
**Describe the work done in detail:**
The work done requires the estimation of the size of the project, effort, and duration that would be needed for the project.

**Has this work been committed to the repository?**
No commits were done to the repository as no code was involved.

**How does the work affect success or completion criteria?**
The work done affects the success of the project as it gives meaningful insights into the project's scope, resource requirements, and timeline. 

Start date and end date:
Start Date: 17/09/23
End Date: 21/09/23

**Comment by KeeHanXiang** [comment]
**Describe the work done in detail.**
The team has completed in estimates of the project in terms of size, effort and duration.

**Has this work been committed to the repository?**
No work is needed to commit to the repository.

**How does the work affect success or completion criteria?**
It helps with an estimation of the work done and the client's payment.

Start date and end date:
[Start Date: 17/09/23]
[End Date: 21/09/23]

**Comment by ThJin** [comment]
Describe the work done in detail.
The work involved the team members doing estimation based on the project's scope and complexity.

Has this work been committed to the repository?
The work does not involve any code. Therefore, no repository commits is needed.

How does the work affect success or completion criteria?
The work provides accurate estimations that ensures effective project planning and resource allocation. 

Start date and end date:
[Start Date: 17/09/23]
[End Date: 21/09/23]
