### ISSUE TITLE
[1.2] Requirements Elicitation

### ISSUE THREAD

**Issue by ImUrGit** [lowyisan/INF2001_P6-6#52]
**Task title** ID: #11

**What is the task about?** This task involves gathering information that is integral to the project.

 **What are the goals of the task?** The goals include identifying the requirements the client would want, those that are written, said, researched, and implied. This task overlooks the team asking questions to clarify any of their doubts with the client in hopes for them to derive the finalised requirements for the project.

**Success or completion criteria:** Successful completion of this task involves compiling and finalising a list of requirements for the project.

**Allocated time**: 17 days

**Start date and end date:** [Start Date: 31/08/23], [End Date: 14/09/23]

**Owner**: All

**Status of the task:** Completed

**Priority**: High

**Comment by ImUrGit** [comment]
**Describe the work done in detail.**
The team has completed identifying what could be some of the requirements that the client would want to have in the system. The team has also came up with some requirements based on the project brief given as well.

**Has this work been committed to the repository?**
No work is needed to commit to the repository.

**How does the work affect success or completion criteria?**
It is important to internalize the project brief as it will pave the way on what the initial requirements would be. Additionally, ideating before meeting the client is good as it can help to somewhat understand the aircon service industry as the team will be asking ourselves questions.

**Start date and end date:**
[Start Date: 31/08/23]
[End Date: 14/09/23]

**Comment by lowyisan** [comment]
**Describe the work done in detail:**
The work done includes gathering some functional and non-functional requirements and crafting questions to ask the client to improve on the requirements.

**Has this work been committed to the repository?**
No, this task do not involve code changes. Therefore, no commits were made to the repository for this task.

**How does the work affect success or completion criteria?**
Crafting questions for the client help us have a better sense of all requirements needed to develop a holistic approach to developing the product.

Start date and end date:
Start Date: 31/08/23
End Date: 14/09/23

**Comment by Magic1sarap** [comment]
**Describe the work done in detail:**
Brainstorming and crafting questions as a team to be presented to client as a means to probe specific needs. 

**Has this work been committed to the repository?**
No, the task does not involve code changes. 

**How does the work affect success or completion criteria?**
In the aim to create a solution that the client desires, the questions in lieu should solicit or pinpoint areas of requirement that may need more attention or concern within the development process.  

Start date and end date:
Start Date: 31/08/23
End Date: 14/09/23

**Comment by mvchello** [comment]
**Describe the work done in detail:**
Together with the team, gathering requirements that would need to be turned into features for the product was done for this task. This task encompasses gathering of requirements even through the meeting and follow-up with the client.

**Has this work been committed to the repository?**
No, the task does not involve code changes.

**How does the work affect success or completion criteria?**
This task enabled the team to successfully sieve out the requirements that the client wants to be implemented in the future. The success of this task contributes to the success of the project as a whole as it directs the team in the right direction.

**Start date and end date:**
Start Date: 31/08/23
End Date: 14/09/23

**Comment by mvchello** [comment]
.

**Comment by KeeHanXiang** [comment]
**Describe the work done in detail.**
The team discussed gathering both functional and non-functional requirements as well as posing questions that were to be asked of the client.

**Has this work been committed to the repository?**
No work is needed to commit to the repository.

**How does the work affect success or completion criteria?**
With the clarification of the project needs to suit the client's needs, we can better understand which approach we should steer towards.

Start date and end date:
[Start Date: 31/08/23]
[End Date: 14/09/23]

**Comment by ThJin** [comment]
Describe the work done in detail.
The work involved in gathering information integral to the project's success.

Has this work been committed to the repository?
The work does not involve any code. Therefore, no repository commits is needed.

How does the work affect success or completion criteria?
The work provides a list of information that can be used to address all necessary element and aligning with the client's expectations.

Start date and end date:
[Start Date: 31/08/23]
[End Date: 14/09/23]
