### ISSUE TITLE
[1.2.1.1] Formulate Questions to Ask Client

### ISSUE THREAD

**Issue by ImUrGit** [lowyisan/INF2001_P6-6#53]
**Task title ID:** #13

**What is the task about?** This task involves coming up with questions that are to be asked to the client in order to dismiss any possible false ideation. This task requires formulating different sets of questions that will be asked during the meet-up, as well as the the follow-up with the client.

**What are the goals of the task?** The goals include rectifying any uncertainties with the client to further the development process of the project. 

**Success or completion criteria:** Successful completion of this task involves compiling a list of effective questions to be asked to the client.

**Allocated time:** 12 days

**Start date and end date:** [Start Date: 31/08/23], [End Date: 11/09/23]

**Owner:** All

**Status of the task:** Completed

**Priority:** High

**Comment by ImUrGit** [comment]
**Describe the work done in detail.**
The team has completed formulating questions that the team would like to ask the client to move forward with the project. The team has also made sure to ask a wide range of questions in order to get more insights.

**Has this work been committed to the repository?**
No work is needed to commit to the repository.

**How does the work affect success or completion criteria?**
It is important to ask questions relevant to the client and to also make sure the questions the team asks should be something that the team is not able to answer or assume.

**Start date and end date:**
[Start Date: 31/08/23]
[End Date: 11/09/23]

**Comment by lowyisan** [comment]
**Describe the work done in detail:**
The work done involves coming up with some questions I have gathered based off reading the brief in gain a better understanding of the project needs.

**Has this work been committed to the repository?**
No, this task do not involve code changes. Therefore, no commits were made to the repository for this task.

**How does the work affect success or completion criteria?**
This helps the team to clarify all our doubts and in improving the requirements.

Start date and end date:
[Start Date: 31/08/23]
[End Date: 11/09/23]

**Comment by Magic1sarap** [comment]
**Describe the work done in detail:**
Crafted questions that are designed to probe deeper and gain clarity to some of the presented requirements. 

**Has this work been committed to the repository?**
No, this task do not involve code changes. Therefore, no commits were made to the repository for this task.

**How does the work affect success or completion criteria?**
This helps in defining the functions that will be involved in the implementation phase of the development process.  

Start date and end date:
[Start Date: 31/08/23]
[End Date: 11/09/23]

**Comment by mvchello** [comment]
**Describe the work done in detail:**
The team consolidated a few practical questions to be asked to the client in hopes of clearing any uncertainties that might decrease the quality of the product.

**Has this work been committed to the repository?**
No, the task does not involve code changes.

**How does the work affect success or completion criteria?**
The work done affects the success as without consolidating the questions, the meeting with the client would go to waste. Time would not have been used up effectively, and the team;s doubts on certain things would not have been clarified.

**Start date and end date:**
Start Date: 31/08/23
End Date: 11/09/23

**Comment by mvchello** [comment]
.

**Comment by KeeHanXiang** [comment]
**Describe the work done in detail:**
During our team meeting, we engaged in a thorough discussion and diligently explored various aspects, with a particular focus on identifying critical details that warrant attention. In our commitment to enhancing clarity and addressing any lingering uncertainties, we've collectively decided to compile these essential questions. These queries will be thoughtfully presented to our valued client, ensuring a comprehensive understanding of the project's requirements and objectives.

**Has this work been committed to the repository?**
No, the task does not involve code changes.

**How does the work affect success or completion criteria?**
The work done aligns us with the requirements of the project

Start date and end date:
Start Date: 31/08/23
End Date: 11/09/23

**Comment by ThJin** [comment]
Describe the work done in detail.
The work involved the team meeting up to formulate a series of questions to asked the client. These questions aims to clarify any potential misunderstanding or misconceptions.

Has this work been committed to the repository?
The work does not involve any code. Therefore, no repository commits is needed.

How does the work affect success or completion criteria?
The work provides a list of questions in addressing uncertainties and ensuring a clear understanding between the team and the client.  

Start date and end date:
[Start Date: 31/08/23]
[End Date: 11/09/23]
