### ISSUE TITLE
[1.2.1.2] Client Meeting #1

### ISSUE THREAD

**Issue by ImUrGit** [lowyisan/INF2001_P6-6#54]
**Task title ID:** #14

**What is the task about?** This task involves meeting with the client to clear any uncertainties that have been compiled by the team members, as well as to decide the next steps for the project.

**What are the goals of the task?** The goals include clarifying doubts and proposing suggestions to the client. From this, the following steps needed to be taken for the project will also be derived from the meeting.

**Success or completion criteria:** Successful completion of this task involves a list of answers to the questions asked to the client.

**Allocated time:** 1 day

**Start date and end date:** [Start Date: 06/09/23], [End Date: 06/09/23]

**Owner:** All

**Status of the task:** Completed

**Priority:** High

**Comment by ImUrGit** [comment]
**Describe the work done in detail.**
The team has met up with the client to clear doubts that the team has. The team has gained valuable insights from the client meeting. However, some parts may not have been discussed due to time constraint. Therefore, the team will send a follow up email to clear the remaining doubts.

**Has this work been committed to the repository?**
No work is needed to commit to the repository.

**How does the work affect success or completion criteria?**
It is important to address any uncertainties so that the team can define the next steps or next course of action. If the team succeeds in this, it will definitely maintain a positive relationship with the client. 

**Start date and end date:**
[Start Date: 06/09/23]
[End Date: 06/09/23]

**Comment by lowyisan** [comment]
**Describe the work done in detail.**
The work done includes attending the meeting and asking the questions that I have crafted previously to the client.

**Has this work been committed to the repository?**
No work is needed to commit to the repository.

**How does the work affect success or completion criteria?**
It allows us to take down the important points or concerns the client have to help us in our requirements elicitation stage.

**Start date and end date:**
[Start Date: 06/09/23]
[End Date: 06/09/23]

**Comment by Magic1sarap** [comment]
**Describe the work done in detail.**
We have attended the meeting with the client online and shared our questions that we have previously crafted.

**Has this work been committed to the repository?**
This task does not involve code changes, therefore, no work has been committed to the repository. 

**How does the work affect success or completion criteria?**
Allows a more narrowed and specific assessment for the requirements needed in our solution/project. 

Start date and end date:
[Start Date: 06/09/23]
[End Date: 06/09/23]

**Comment by mvchello** [comment]
**Describe the work done in detail:**
Meeting with the client was held online, however, not all of the questions were answered as there were other teams on the call as well. Agreed to have another meeting with the client which is considered as a physical follow-up.

**Has this work been committed to the repository?**
No, the task does not involve code changes.

**How does the work affect success or completion criteria?**
The work done ensures that not only were the doubts of the team being clarified but also to get to know more about the client's view on all of the points that were raised. This helps the team to cater the implemented features more toward the client's liking. 

**Start date and end date:**
Start Date: 06/09/23
End Date: 06/09/23

**Comment by mvchello** [comment]
.

**Comment by KeeHanXiang** [comment]
**Describe the work done in detail:**
A Zoom meeting was conducted with the client and we posed questions that we had gathered from our internal meeting previously

**Has this work been committed to the repository?**
No, the task does not involve code changes.

**How does the work affect success or completion criteria?**
The work done ensures that our doubts were clarified and client's need were highlighted

Start date and end date:
Start Date: 06/09/23
End Date: 06/09/23

**Comment by ThJin** [comment]
Describe the work done in detail.
The work involved meeting with the client to address any uncertainties or questions the team has prepared.

Has this work been committed to the repository?
The work does not involve any code. Therefore, no repository commits is needed.

How does the work affect success or completion criteria?
The work provides an answer to the questions raised, providing clarity to guide the team in moving forward with the project.

Start date and end date:
[Start Date: 06/09/23]
[End Date: 06/09/23]
