### ISSUE TITLE
[1.1] Understand the Project

### ISSUE THREAD

**Issue by ImUrGit** [lowyisan/INF2001_P6-6#55]
**Task title ID:** #01

**What is the task about?** This task involves comprehending the entire project, including its scope, objectives, and requirements. Additionally, it involves the team researching more about the client's current circumstances as well as information that might be useful to the project. These are all done to lay the foundation for further project planning and execution.

**What are the goals of the task?** The goal is to gain a thorough understanding of the project's purpose, client's expectations, and overall context to guide subsequent project activities effectively.

**Success or completion criteria:** This task is considered successful when all team members have a clear understanding of the project's scope, objectives, and initial requirements. Gathered information that is useful to the project would also contribute to its success.

**Allocated time:** 16 days

**Start date and end date:** [Start Date: 31/08/23], [End Date:12/09/23]

**Owner:** All

**Status of the task:** Completed

**Priority:** Medium

**Comment by ImUrGit** [comment]
**Describe the work done in detail.**
The team has met up together and looked at the project brief provided by the client. The team has also received a briefing from the professor on what the team needs to do for the project in this module.

**Has this work been committed to the repository?**
No work is needed to commit to the repository.

**How does the work affect success or completion criteria?**
It is important to know the goal for the module and what we are to be doing as it is graded for the team.

**Start date and end date:**
[Start Date: 31/08/23]
[End Date: 12/09/23]

**Comment by lowyisan** [comment]
**Describe the work done in detail.**
The work done includes attending the team meeting to discuss the brief and any concerns we might have about the project and the next steps we should take.

**Has this work been committed to the repository?**
No work is needed to commit to the repository.

**How does the work affect success or completion criteria?**
It allows the team be on the same page for us to know the goals we should strive for in this module.

**Start date and end date:**
[Start Date: 31/08/23]
[End Date: 12/09/23]

**Comment by Magic1sarap** [comment]
**Describe the work done in detail.**
The work done includes meeting with the team to discuss and understand the project at hand further.

**Has this work been committed to the repository?**
The task does not involve any code changes. Therefore, no work has been committed to the repository. 

**How does the work affect success or completion criteria?**
Gathers the team to a united goal and aim, towards the success of this project. 

Start date and end date:
[Start Date: 31/08/23]
[End Date: 12/09/23]

**Comment by mvchello** [comment]
**Describe the work done in detail:**
The team met up to discuss their views on the project. They have also taken the time to digest and internalise the requirements of the client and what is expected of them from this project.

**Has this work been committed to the repository?**
No, the task does not involve code changes.

**How does the work affect success or completion criteria?**
The work done affects the completion of the whole project as it is where the fundamentals of the project is being built. By making sure that everyone is on the same page, the team will be able to move forward more efficiently.

**Start date and end date:**
Start Date: 31/08/23
End Date: 12/09/23

**Comment by mvchello** [comment]
.

**Comment by KeeHanXiang** [comment]
**Describe the work done in detail.**
The team met up in order to discuss plans and brainstorm ideas moving forward.

**Has this work been committed to the repository?**
No work is needed to commit to the repository.

**How does the work affect success or completion criteria?**
It provides the team with an idea or a direction to work toward.

Start date and end date:
[Start Date: 31/08/23]
[End Date: 12/09/23]

**Comment by ThJin** [comment]
Describe the work done in detail.
The work involved the team members meeting up and discussing the entire project, encompassing its scope, objectives, and requirements.

Has this work been committed to the repository?
The work does not involve any code. Therefore, no repository commits is needed.

How does the work affect success or completion criteria?
The work provides all team members with a clear understanding of the project's scope, objectives, and initial requirements.

Start date and end date:
[Start Date: 31/08/23]
[End Date: 12/09/23]
