### ISSUE TITLE
[1.1.1] Understand Project Scope

### ISSUE THREAD

**Issue by ImUrGit** [lowyisan/INF2001_P6-6#56]
**Task title ID:** #02

**What is the task about?** This task involves delving into the project's scope specifically to define the boundaries and limitations of the project.

**What are the goals of the task?** The goal is to clearly define what the project will and will not encompass, ensuring alignment with client expectations.

**Success or completion criteria:** This task is considered successful when the project's scope is documented and agreed upon by the project team and client.

**Allocated time:** 13 days

**Start date and end date:** [Start Date: 31/08/23], [End Date: 12/09/23]

**Owner:** All

**Status of the task:** Completed

**Priority:** Medium

**Comment by ImUrGit** [comment]
**Describe the work done in detail.**
The team has completed understanding what the limitations and what the boundaries should be for the project scope.

**Has this work been committed to the repository?**
No work is needed to commit to the repository.

**How does the work affect success or completion criteria?**
It is important for the team to understand what the project scope is in order to understand what the team should be working on.

**Start date and end date:**
[Start Date: 31/08/23]
[End Date: 12/09/23]

**Comment by lowyisan** [comment]
**Describe the work done in detail:**
The work done includes understanding the needs of the project and having a clearer view of the next steps to take.

**Has this work been committed to the repository?**
No, this task do not involve code changes. Therefore, no commits were made to the repository for this task.

**How does the work affect success or completion criteria?**
This helps us plan our next steps since everyone is on the same page, and start planning for client meetings and developing the requirements.

Start date and end date:
Start Date: 31/08/23
End Date: 05/09/23

**Comment by Magic1sarap** [comment]
**Describe the work done in detail:**
The work done involves narrowing down the needs of the project as well as setting a clear view for what is at stake. 

**Has this work been committed to the repository?**
No work has been committed to the repository as this task does not involve code changes. 

**How does the work affect success or completion criteria?**
This helps us in progression towards the project as well as prepare for the client meetings. 

Start date and end date:
Start Date: 31/08/23
End Date: 05/09/23

**Comment by mvchello** [comment]
**Describe the work done in detail:**
The team needed to understand what would be covered in the project, therefore establishing the strengths and limitations, to see what can be worked on.

**Has this work been committed to the repository?**
No, the task does not involve code changes.

**How does the work affect success or completion criteria?**
The work done helps to set a clear view on what needs to be done for the project by the team.

**Start date and end date:**
Start Date: 31/08/23
End Date: 12/09/23

**Comment by mvchello** [comment]
.

**Comment by KeeHanXiang** [comment]
**Describe the work done in detail:**
The team needed to understand in depth and in detail the requirements and deliverables to be submitted

**Has this work been committed to the repository?**
No, the task does not involve code changes.

**How does the work affect success or completion criteria?**
The work done provides a structure and an idea of how the project should be approached

Start date and end date:
Start Date: 31/08/23
End Date: 12/09/23

**Comment by ThJin** [comment]
Describe the work done in detail.
The work involved a thorough analysis of the project's scope, with an emphasis on identifying its boundaries and restrictions.

Has this work been committed to the repository?
The work does not involve any code. Therefore, no repository commits is needed.

How does the work affect success or completion criteria?
The work lays the groundwork for a successful project execution and offers precise definitions to avoid misunderstandings.

Start date and end date:
[Start Date: 31/08/23]
[End Date: 12/09/23]
