### ISSUE TITLE
[1.1.1.3] Understand Client's Current Job Allocation Process

### ISSUE THREAD

**Issue by Magic1sarap** [lowyisan/INF2001_P6-6#57]
**Task title ID:** #05

**What is the task about?** This task involves gaining a comprehensive understanding of the client's existing workflow and methods for assigning jobs to employees based on the client brief.

**What are the goals of the task?**  The goal is to understand the client's current system, including its strengths and weaknesses, in order to identify areas where the new system can provide improvements.

**Success or completion criteria:** This task is considered successful when a summary of the client's current system is compiled. This would require confirmation from the client.

**Allocated time:** 13 day

**Start date and end date:** [Start Date: 31/08/23], [End Date: 12/09/23]

**Owner:** Han Xiang

**Status of the task:** To-Do

**Priority:** Medium

**Comment by KeeHanXiang** [comment]
**Describe the work done in detail:**
The work done involves gaining a deeper insight of the client's current job allocation process.

**Has this work been committed to the repository?**
No, this task does not involve code changes. Therefore, no commits were made to the repository for this task.

**How does the work affect success or completion criteria?**
This allows us to understand the improvements of how our product can better improve the client's system.

Start date and end date:
Start Date: 31/08/23
End Date: 12/09/23
