### ISSUE TITLE
[1.4.1] Introduction

### ISSUE THREAD

**Issue by Magic1sarap** [lowyisan/INF2001_P6-6#60]
**Task title ID:** #28

**What is the task about?** This task introduces the product to the readers. It covers the scope, related background research, intended audience, and the overview of the product.

**What are the goals of the task?** This task seeks to inform readers about integral information that they need to know regarding the product before getting deeper into the documentation. This presents the reader to have some background knowledge that is crucial for them to understand what is going on.

**Success or completion criteria:** The success of the task depends on readers being able to understand the product's scope and the related information that is required.

**Allocated time:** 5 days

**Start date and end date:** [Start Date: 11/09/23], [End Date: 13/09/23]

**Owner:** Isaac & Michelle

**Status of the task:** To-Do

**Priority:** High

**Comment by Magic1sarap** [comment]
**Describe the work done in detail:**
Written and crafted the introduction providing context to the project, the main focuses as well as the purpose for the project. 

**Has this work been committed to the repository?**
No commits were done to the repository as no code was involved.

**How does the work affect success or completion criteria?**
Helps to introduce the document's purpose and aim as well as its context towards its readers.


Start date and end date:
Start Date: 11/09/23
End Date: 13/09/23

**Comment by mvchello** [comment]
**Describe the work done in detail:**
Written the introduction, encompassing the scope of the product, research that has been done for the project, an overview of the project, it's target audience, and acknowledgements of the resources that have been tapped into for the project.

**Has this work been committed to the repository?**
No commits were done to the repository as no code was involved.

**How does the work affect success or completion criteria?**
The work done helps to give readers a good heads up on what they will be in for.


Start date and end date:
Start Date: 11/09/23
End Date: 13/09/23
