### ISSUE TITLE
[1.3] Project Management

### ISSUE THREAD

**Issue by ThJin** [lowyisan/INF2001_P6-6#79]
**Task title ID:** #22

**What is the task about?** This task requires efficient planning, organising, and tracking of the tasks needed to be done for the project.

**What are the goals of the task?** The goal of this task is to effectively help the team achieve their goals, stay organized, and meet deadlines, ultimately improving productivity and reducing stress.

**Success or completion criteria:** The success of this task is determined through the clearance of tasks delegated to each team member before the stipulated deadlines.

**Allocated time:** 2 days

**Start date and end date:** [Start Date: 11/09/23], [End Date: 12/09/23]

**Owner:** Han Xiang & Jin Hao

**Status of the task:** To-Do

**Priority:** Low

**Comment by KeeHanXiang** [comment]
**Describe the work done in detail:**
The work done involves planning and jotting down tasks to be done and organizing them for the team

**Has this work been committed to the repository?**
No, this task does not involve code changes. Therefore, no commits were made to the repository for this task.

**How does the work affect success or completion criteria?**
This helps tasks to be delegated to each member for drafting and completion

Start date and end date:
Start Date: 11/09/23
End Date: 12/09/23

**Comment by ThJin** [comment]
Describe the work done in detail.
The work involves effective task planning, organisation, and tracking for a project. It focuses on making sure that the team can manage work efficiently to fulfil deadlines and goals.

Has this work been committed to the repository?
The work does not involve any code. Therefore, no repository commits is needed.

How does the work affect success or completion criteria?
The work provides tasks delegated to each team member with task planning to ensure the team can meet their objectives.

Start date and end date:
[Start Date: 11/09/23]
[End Date: 12/09/23]
