### ISSUE TITLE
[2.2.3] Creation of Sequence Diagram

### ISSUE THREAD

**Issue by mvchello** [lowyisan/INF2001_P6-6#82]
Task title ID: #82

What is the task about? This task focuses on the creation of sequence diagrams as part of the System Architectural Design. A sequence diagram is a visual representation that illustrates the interactions and sequences of messages or actions between objects or components in the software system during specific use cases or scenarios.

What are the goals of the task?

- Visualize and document how objects or components within the software system interact and communicate during specific use cases or scenarios.
- Create a clear representation of the flow of actions and messages between objects

Success or completion criteria: 

- Comprehensive Sequence Diagrams
- Alignment with Use Cases

Allocated time: 6 days

Start date and end date: [Start Date: 23/10/23], [End Date: 28/10/23]

Owner: Han Xiang & Isaac

Status of the task: To-Do

Priority: Medium

**Comment by KeeHanXiang** [comment]
Describe the work done in detail.
The sequence Diagram has been completed using lucid.

Has this work been committed to the repository?
No work is needed to commit to the repository.

How does the work affect success or completion criteria?
It helps to better see the flow in sequence through the use of use cases and class diagram.

Start date and end date:
[Start Date: 23/10/23]
[End Date: 28/10/23]

**Comment by Magic1sarap** [comment]
Describe the work done in detail:
The sequence Diagram for UC-15 (Manage New Job Assigned) has been completed.

Has this work been committed to the repository?
No, as no code was involved. 

How does the work affect success or completion criteria?
It provides a flow of the user's actions when completing this use case. 

Start date and end date:
[Start Date: 23/10/23]
[End Date: 28/10/23]
