### ISSUE TITLE
[2.3] Documentation

### ISSUE THREAD

**Issue by ThJin** [lowyisan/INF2001_P6-6#84]
What is the task about? This task involves creating and updating documentation related to the project. Including updates from milestone 1 and documentation of Milestone 2 system design.

What are the goals of the task? The goal is to ensure that the documentation is updated and complete.

Success or Completion Criteria: All necessary documentation is updated to the latest and all sub-tasks are completed.

Allocated time: 13 days

Start date and end date: [Start Date: 16/10/23], [End Date: 28/10/23]

Owner: All

Status of the task: To-Do

Priority: Medium

**Comment by mvchello** [comment]
**Describe the work done in detail.**
Documentation of the introduction - product scope changes, component diagram, and project plan update were done for this task.

**Has this work been committed to the repository?**
No work is needed to commit to the repository.

**How does the work affect success or completion criteria?**
It is important to document the mentioned information as it helps to correct and display to whoever the document may concern, a more accurate depiction of the state of the project. Additionally, the team is able to refer to these documentations to get the most up-to-date information regarding the project.

**Start date and end date:**
[Start Date: 16/10/23]
[End Date: 28/10/23]

**Comment by lowyisan** [comment]
**Describe the work done in detail.**
I documented the references and acknowledgements and class diagram and project plan update portion of the Milestone report.

**Has this work been committed to the repository?**
No work is needed to commit to the repository.

**How does the work affect success or completion criteria?**
This helps us keep track of all our work on a single document for all team members to be on the same page and helps to facilitate us to update our work in an accurate manner.

**Start date and end date:**
[Start Date: 16/10/23]
[End Date: 27/10/23]

**Comment by Magic1sarap** [comment]
**Describe the work done in detail.**
I have documented the sequence diagram for UC15 (Use Case 15: Manage new job Assigned).

**Has this work been committed to the repository?**
No, as there was no code involved.

**How does the work affect success or completion criteria?**
Ensures that the sequence diagram is explained with context, as well as to add reference when interpreting the sequence diagram. 

**Start date and end date:**
[Start Date: 16/10/23]
[End Date: 28/10/23]

**Comment by ImUrGit** [comment]
**Describe the work done in detail.**
I have helped in inserting the various diagrams and have contributed in writing up on the component diagram. I have also helped to format the M2 document as well.

**Has this work been committed to the repository?**
No work is needed to commit to the repository.

**How does the work affect success or completion criteria?**
It is important to make sure that the milestone 2 report is properly formatted so that it is easier for readers to go through the report.

**Start date and end date:**
[Start Date: 16/10/23]
[End Date: 28/10/23]

**Comment by ThJin** [comment]
**Describe the work done in detail.**
The work involved creating and updating project-related documentation, incorporating updates from M1 and documenting the M2 system design. 

**Has this work been committed to the repository?**
The work does not involve any code. Therefore, no repository commits is needed.

**How does the work affect success or completion criteria?**
The work ensures the documentation is comprehensive, up to date, and reflective of the project's progress and requirements.

Start date and end date:
[Start Date: 16/10/23]
[End Date: 28/10/23]

**Comment by KeeHanXiang** [comment]
Describe the work done in detail.
The work involved creating the sequence diagram and documenting it.

Has this work been committed to the repository?
The work does not involve any code. Therefore, no repository commits is needed.

How does the work affect success or completion criteria?
Documentation is updated to the latest and all sub-tasks are completed.

Start date and end date:
[Start Date: 16/10/23]
[End Date: 28/10/23]
