### ISSUE TITLE
[2.3.2] Changes in Requirements

### ISSUE THREAD

**Issue by ThJin** [lowyisan/INF2001_P6-6#85]
**What is the task about?** This task involves reviewing the feedback, assessments, and evaluations received during Milestone 1 (M1) and making necessary updates and improvements to the project's components. 

**What are the goals of the task?** The goal is to update the documentation based on the feedback of milestone 1 and ensure the creation of documentation for system design.

**Success or Completion Criteria:** All documentation and sub-tasks are completed.

**Allocated time:** 6 days

**Start date and end date:** [Start Date: 16/10/23], [End Date: 21/10/23]

**Owner:** Alain, Han Xiang, Isaac, Jin Hao

**Status of the task:** To-Do

**Priority:** Medium

**Comment by Magic1sarap** [comment]
**Describe the work done in detail.**
Revised the requirements as needed and in compliance to the M1 feedback.

**Has this work been committed to the repository?**
No, as no code was involved. 

**How does the work affect success or completion criteria?**
To ensure accuracy in the requirement deliverables for this project.

**Start date and end date:**
[Start Date: 16/10/23]
[End Date: 21/10/23]

**Comment by ImUrGit** [comment]
**Describe the work done in detail.**
I have helped in documenting some of the new changes in the requirements based on the M1 feedback.

**Has this work been committed to the repository?**
No work is needed to commit to the repository.

**How does the work affect success or completion criteria?**
It is important to look back on the feedback and document the changes to let the readers know the updates from the last report.

**Start date and end date:**
[Start Date: 17/10/23]
[End Date: 21/10/23]

**Comment by ThJin** [comment]
**Describe the work done in detail.**
The work involved reviewing feedback received during M1 and making essential updates and improvements to various components of the project. 

**Has this work been committed to the repository?**
The work does not involve any code. Therefore, no repository commits is needed.

**How does the work affect success or completion criteria?**
The work ensures the documentation is enhanced, ensuring it accurately represents the project's requirements.

Start date and end date:
[Start Date: 16/10/23]
[End Date: 21/10/23]

**Comment by KeeHanXiang** [comment]
Describe the work done in detail.
Reviewing M1 feedback and changing the requirements as required.

Has this work been committed to the repository?
No, as no code was involved.

How does the work affect success or completion criteria?
To ensure that the document aligns with the project requirements.

Start date and end date:
[Start Date: 16/10/23]
[End Date: 21/10/23]
