### ISSUE TITLE
[2.2.1] Creation of Overall Class Diagram

### ISSUE THREAD

**Issue by ThJin** [lowyisan/INF2001_P6-6#87]
What is the task about? The task involves the documenting of the class diagram comprehensively.

What are the goals of the task? The primary goal is to document the structure of the software system by creating or updating the class diagram. This includes specifying classes, their attributes, methods, and relationships.

Success or Completion Criteria: Provide a well-documented and up-to-date class diagram that accurately represents the structure of the software system. This diagram should clearly depict the classes, their attributes, methods, and relationships.

Allocated time: 9 days

Start date and end date: [Start Date: 20/10/23], [End Date: 28/10/23]

Owner: Jin Hao & Yi San

Status of the task: To-Do

Priority: Medium

**Comment by lowyisan** [comment]
**Describe the work done in detail:**
During this task, I have focused on documenting the foundation class diagram's structure, emphasising the classes, their attributes, and methods. I have also established relationships between the classes to provide a comprehensive overview of the software system's architecture.

**Has this work been committed to the repository?**
No, this task do not involve code changes. Therefore, no commits were made to the repository for this task.

**How does the work affect success or completion criteria?**
 The work completed for this task is a critical step in achieving the project's success criteria. It contributes to the creation of class diagram that accurately represents the software system's structure. This, in turn, ensures that the project's architecture is well-defined and provides a solid foundation for further improvement.

**Start date and end date:**
Start Date: 20/10/23
End Date: 28/10/23

**Comment by ThJin** [comment]
**Describe the work done in detail.**
The work involves thorough record of the class diagram with an emphasis on encapsulating the software system's structure. Where Classes are specified, together with information on their methods, properties, and relationships within the system. 

**Has this work been committed to the repository?**
The work does not involve any code. Therefore, no repository commits is needed.

**How does the work affect success or completion criteria?**
The ensures a well-documented and up-to-date class diagram that accurately depicts the software system's structure.

Start date and end date:
[Start Date: 20/10/23]
[End Date: 28/10/23]
